# docker-compose.yml
version: '3'

services:

    nginx:
        build:
            context: .
            dockerfile: ./dockerfiles/nginx/Dockerfile
        depends_on:
            - backend
        ports:
            - 80:80

    database:
        build:
            context: .
            dockerfile: ./dockerfiles/postgres/Dockerfile
        environment:
            POSTGRES_DB: "codefuturebank"
            POSTGRES_USER: "max"
            POSTGRES_PASSWORD: "123Max123Ma_"
        expose:
            - 5432

    backend:
        build:
            context: .
            dockerfile: ./dockerfiles/web/Dockerfile
        tty: true
        command: python3 -u -m gunicorn codefuture_bank.wsgi -b backend -p 8000
        depends_on:
            - database
        restart: always
        expose:
           - 8000


networks:
    database_network:
        driver: bridge
